roweeena/seir48-homework

Sarah Ruello/week_01/calculator/index.html, Sarah Ruello/week_01/calculator/js/calc.js, Sarah Ruello/week_01/strings/index.html, Sarah Ruello/week_01/strings/js/strings.js
5. Git was a bit confusing as some things have changed, they are also asking for tokens instead of passwords now, which complicates things. Some of the string functions were a bit too much for me.
Git & two of the string functions.
The string function solutions!
About 2 hrs.
=> Sarah's Tuesday homework

Alex Poulsen/week_01/calculator/calculator.js, Alex Poulsen/week_01/calculator/index.html, Alex Poulsen/week_01/index.html, Alex Poulsen/week_01/strings.js
5 ish
Strings methods and regex in the final strings problem
Tips for Regex would be greatly appreciated! 
2.5-3 hours
=> Calculator and Strings Homework

Jonny Wermut/week_01/Strings/index.html, Jonny Wermut/week_01/Strings/js/exercises.js, Jonny Wermut/week_01/raindrops_warmup/index.html, Jonny Wermut/week_01/raindrops_warmup/js/exercises.js, Jonny Wermut/week_01/theCalculator/index.html, Jonny Wermut/week_01/theCalculator/js/exercises.js
3
Didn't finish the strings exercises but if I gave it more time I probably could have.
Nothing really. I tested the calculator part and it works. Always curious to learn if there are better ways of doing things.
Not right now.
Calculator took me 60-90 mins.
=> Week 1 Day 2 Homework

Goutham Masavarapu/week_01/calculator/index.html, Goutham Masavarapu/week_01/calculator/js/exercises.js
=> Week1/21sep- calculator Homework

Matthew Schultz/week_01/Strings/index.html, Matthew Schultz/week_01/Strings/js/strings.js, Matthew Schultz/week_01/calculator/index.html, Matthew Schultz/week_01/calculator/js/calculator.js
- 5
- Remembering to use 'return' to store the values.
- 
- 
- 2 hours although I only got through the first exercise in Strings
=> Calculator and Strings

Derek Wei/warmups/week_01/raindrops/index.html, Derek Wei/warmups/week_01/raindrops/js/raindrops.js, Derek Wei/week_01/calculator/index.html, Derek Wei/week_01/calculator/js/calculator.js, Derek Wei/week_01/strings/index.html, Derek Wei/week_01/strings/js/strings.js
calculator 3
strings 8
strings.js
mixUp - tried using string indices str[i] to manipulate strings before finding the .slice function
notBad - took a long time to find regular expressions
strings.js
mixUp function - line 39
Is there a method using conditionals, loops and str[i]?
fixStart function - line 60
Is there a way to ignore cases so that the following outputs work?
fixStart("Babble") => Ba\**le
fixStart("baBbLe") => ba\**Le
notBad function - line 121
Is there a method …
=> wk1 day 2 homework - calculator and strings

Kundai Khuleya/warmups/Raindrops/index.html, Kundai Khuleya/warmups/Raindrops/raindrops.js, Kundai Khuleya/week_1/calculator/js/mainexercises.js, Kundai Khuleya/week_1/strings/js/mainexercises.js
- 10/10 
- I could not see my code in the console. I also think I made a mistake creating the files and folders. I know how to use mkdir and cat and cd but I am not sure if I know when to create a file and when to use touch. I also had a hard time getting Ctl + L to work. When I type it in I get a new line not a clear page. 
- Could we do functions again. I think I don't fully get them.
- Is there anything that you'd like some further information on? how to pick which introductory keyword to use and why when I look up some problems on the …
=> calculator homework

Angeline Polidano/week_1/calculator/index.html, Angeline Polidano/week_1/calculator/js/main.exercises.js
- 9
- functions are pretty new to me and I'm not very familiar with JS calculations.
- 
- the second question in my JS code. 
- functions, calculations, strings.
- How to approach the questions, though process, to simplify the steps. I think I make it too complicated in my head before approaching the question.
- 
-
I was doing homework/ revision until 12:30am. revising variables and functions.
Then I spent around 1.5 hours trying to apply that …
=> my calculator homework

Sarah Ruello/week_01/calculator/index.html, Sarah Ruello/week_01/calculator/js/calc.js, Sarah Ruello/week_01/strings/index.html, Sarah Ruello/week_01/strings/js/strings.js
=> Fixed FixStart & NotBad

Ivan Veselinov/calculator/index.html, Ivan Veselinov/calculator/js/exercise.js, Ivan Veselinov/warmups/22.09.2021/index.html, Ivan Veselinov/warmups/22.09.2021/js/exercise.js
=> My first Homework Calculator

Muhammadhasan Al Asady/week_1/calculator/index.html, Muhammadhasan Al Asady/week_1/calculator/js/exercise.js
-8.5
- Just understanding when to use certain words like "const", "function", and with the IF statements coming in makes it even harder to understand.
- 
- functions
5 hours, and i didn't finish it. I had an error with my HTML file that wouldn't allow me to see the console in browser
=> week_1_homework

Ehsan Hassankiadeh/week-01/calculator/js/exercises.js, Ehsan Hassankiadeh/week-01/index.html
- 5.6
- i have not done the strings unfortunately
- no but i would like to know the most optimum solution 
- 1.5 hour almost
=> calculator Week-1

Keith Ho/week_1/Day_2/calculator/index.html, Keith Ho/week_1/Day_2/calculator/js/exercises.js, Keith Ho/week_1/Day_2/strings/index.html, Keith Ho/week_1/Day_2/strings/js/exercises.js
6
I was struggled with Function FixStart and NotBad.
Please look into function FixStart, how do I use For loop in the function?? How do I loop through string, search and replace the same value in the string in JS?
What's Regular Expression (Regex) ?
4 hours.
=> Keith_homework_calculators_and_strings

Dean Scotthorne/Week-01/calculator/index.html, Dean Scotthorne/Week-01/calculator/js/calculator.js, Dean Scotthorne/Week-01/strings/index.html, Dean Scotthorne/Week-01/strings/js/strings.js
7/10
part 2 calculator function
part 2 calculator function
functions as parameters
5 hours :( haha
=> Calculator & Strings Homework

Daniel Choe/Week_01/Homework_01/index.html, Daniel Choe/Week_01/Homework_01/js/exercises.js
7.51
Yes, especially in part B of the homework.
Yes, the code for the fixStart function please.
Yes, information on how to use the push method to add parts of a string. 
Around 2 hours. I was stuck mainly on the fixStart function.
=> Calculator Homework!

Jonny Wermut/week_01/arraysAndFunctions/index.html, Jonny Wermut/week_01/arraysAndFunctions/js/exercises.js
7
Nothing in particular
Nothing in particular
Not at the moment
2 hours
=> Adding the word guesser

Sarah Ruello/week_01/arrays/index.html, Sarah Ruello/week_01/arrays/js/arrays.js, Sarah Ruello/week_01/strings/js/strings.js, Sarah Ruello/week_01/warmup/js/warmup.js, Sarah Ruello/week_01/warmup/warmup.html, Sarah Ruello/week_01/wordguesser/index.html, Sarah Ruello/week_01/wordguesser/js/script.js, Warmups/day_04/index.html, Warmups/day_04/js/main.js
4
finding a way to print success or fail whilst still looping through the array. went with a boolean flag to enable the loop to halt.
2 hours
=> Wednesday's homework 

Aleksandr Kuzmin/arrays/index.html, Aleksandr Kuzmin/arrays/js/homework.js, Aleksandr Kuzmin/strings/js/homework.js
- 7 out 10
- I still struggle with using a loop inside of a loop
Multiply and Sum and also longest string ( I only manage to compare with a second string)
- logic behind loop inside a loop
- 2.5- 3hours
=> Homework from wednesday

Daniel Choe/Week_01/Homework_02/index.html, Daniel Choe/Week_01/Homework_02/js/exercises.js
7.5
Uncovering new methods to solve the problems.
Nothing in particular.
Not at this stage.
Around 1 hour.
=> Homework 23/9/21

Keith Ho/week_1/day_3/array_and_functions/index.html, Keith Ho/week_1/day_3/array_and_functions/js/exercises.js, Keith Ho/week_1/day_3/homework_the_word_guesser/index.html, Keith Ho/week_1/day_3/homework_the_word_guesser/js/exercises.js, Keith Ho/week_1/day_3/warmup_exercises/index.html, Keith Ho/week_1/day_3/warmup_exercises/js/exercises.js
8
struggled with bonus in word guess, I don't know how to set up a else condition in a for loop when guess letter is right.
can you walk us through with the solution on Wheel of Fortune and Hangman?
5 hours
=> Homework for day_3

Matthew Schultz/week_01/arrays/arrays.html, Matthew Schultz/week_01/arrays/js/arrays.js
5
Initially struggled with number 6 but but I was trying too much weird stuff and when I googled it it gave me a far more obvious answer
not particularly
not this time
just over two hours
=> array homework

Angeline Polidano/week_1/arrays/index.html, Angeline Polidano/week_1/arrays/js/exercise.js, Angeline Polidano/week_1/calculator/js/exercises.js
5/6
- I think it would be great to look into this. My approach, syntax and data types.
- Would love to go into this with a TA- 
- My homework didn't look like Ivans but I want to know if mine is explicitly incorrect or just a different approach and with correct syntax would it be fixed?
- 
- Arrays
I was revising yesterdays lesson most of the evening. I spend maybe 40 minutes on arrays.
=> Arrays Homework

Jonny Wermut/week_01/objects/index.html, Jonny Wermut/week_01/objects/js/exercises.js
7
Yes. Passing in variables as a key using [] and not '.' blew my mind. Thanks Pat for getting me unstuck.
Nothing in particular.
Not right now
3+ hours
=> Day 4 homework. Not yet attempted CC checker or bank challenge

Sarah Ruello/week_01/objects/js/objects.js, Sarah Ruello/week_01/warmup/js/warmup.js, Sarah Ruello/week_01/warmup/warmup.html
=> Friday 24/9 Warmup

Bernardo Martin/Week1/Array_Objects_Functions/index.html, Bernardo Martin/Week1/Array_Objects_Functions/js/exercise.js, Bernardo Martin/Week1/Array_and_Function/index.html, Bernardo Martin/Week1/Array_and_Function/js/excercise.js
- How difficult did you find this (out of 10)? 8
- Was there anything that you struggled with? I couldn't find a way to add all the numbers within an array
- Is there any particular code you want me to look into? Exercise Bonus 5 returns the reversal of the string but each word is split by a ','. I suppose there's some way to get rid of that
- Is there anything that you'd like some further information on? At this stage I think during the class I will sort my doubts
- Roughly how long did it take? 2/3 hours
=> Array_and_Functions_Homework

Keith Ho/week_1/day_4/credit_card_validation/index.html, Keith Ho/week_1/day_4/credit_card_validation/js/exercises.js, Keith Ho/week_1/day_4/geometry_function_lab/index.html, Keith Ho/week_1/day_4/geometry_function_lab/js/exercises.js, Keith Ho/week_1/day_4/javascript_bank/index.html, Keith Ho/week_1/day_4/javascript_bank/js/exercises.js, Keith Ho/week_1/day_4/the_cash_register/index.html, Keith Ho/week_1/day_4/the_cash_register/js/exercises.js, Keith Ho/week_1/day_4/warmup_exercises/index.html, Keith Ho/week_1/day_4/warmup_exercises/js/exercises.js
=> homework_days_4

Aleksandr Kuzmin/objects/index.html, Aleksandr Kuzmin/objects/js/homework.js
=> Homework thursday

Goutham Masavarapu/week_01/warmups/warmup3/index.html, Goutham Masavarapu/week_01/warmups/warmup3/js/warmup.js
=> warmup day 3 -leap year

Jonny Wermut/week_01/javascriptBank/index.html, Jonny Wermut/week_01/javascriptBank/js/jsbank.js, Jonny Wermut/week_01/mta/index.html, Jonny Wermut/week_01/mta/js/mta.js, Jonny Wermut/week_01/objects/js/exercises.js
8
Nothing in particular just lots of little functions make it easier.
Open to ideas if there are easier ways to structure or organise the code.
Not atm
2 hours
=> Submitting MTA task

Dean Scotthorne/Week-01/Day-4/index.html, Dean Scotthorne/Week-01/Day-4/js/main.js, Warmups/day_04/index.html, Warmups/day_04/js/main.js
7
i struggled with the array of objects on the shopping cart problem.
Can you also look at the triangle problem, I think i misread the question, was it asking for it 'individual functions for each triangle type' or just the 'one function to do all of them'.
The function i made worked, but i feel there may have been an easier way? 
iterating on for loops and objects
4 hours
=> day 4 homework

Keith Ho/week_1/day_5/MTA_Lab/index.html, Keith Ho/week_1/day_5/MTA_Lab/js/exercises.js, Keith Ho/week_1/day_5/warmup_exercises/index.html, Keith Ho/week_1/day_5/warmup_exercises/js/exercises.js
7
I haven't done any customer input validation yet.
2 hours
=> homework_MTA_Lab

Jonny Wermut/week_02/homework/catWalk/catwalk.html, Jonny Wermut/week_02/homework/catWalk/js/catwalk.js
- 4
- yes - I couldn't get my while loop to work so that the cat would turn around and start walking the other way.
- Would love to know how the cat can turn around
- no
- 60 mins
=> Cat walks across screen.

Sarah Ruello/week_02/catwalk/animation.html, Sarah Ruello/week_02/catwalk/js/script.js
- 12
- WALK BACKWARDS FOR THE LOVE OF GOD
- too long
=> cursed cat

Keith Ho/week_2/day_3/animation/index.html, Keith Ho/week_2/day_3/animation/js/exercises.js, Keith Ho/week_2/day_3/warmup_exercises/index.html, Keith Ho/week_2/day_3/warmup_exercises/js/exercises.js
9, I haven't done Bonus 4 yet
in Bonus 3: i wanna change the cat image to another cat dance image in the middle of screen, but it seems like setInterval functions is not working…
setInterval and clearInterval
5 hours
=> homework_the_cat_walk

Ivan Veselinov/homework's/week_04/calculator/calculator.rb, Ivan Veselinov/warmup's/warmups_04/11.10.2021/index.html, Ivan Veselinov/warmup's/warmups_04/11.10.2021/js/exercise.js
Hi Pat and Rowena, i forgot to mention ive had a problem with ATM Exercise if you find a time please have a look. Thank you
- 1
- no
- no into this one but into ATM please
- no
- 30 mins
=> Ruby Calculator done

Keith Ho/week_4/day_1/bmi_calculator.rb, Keith Ho/week_4/day_1/calculator.rb, Keith Ho/week_4/day_1/mortgage_calculator.rb, Keith Ho/week_4/day_1/myREPL/keith_repl.rb, Keith Ho/week_4/day_1/trip_calculator.rb, Keith Ho/week_4/day_1/warmup_exercises/index.html, Keith Ho/week_4/day_1/warmup_exercises/js/exercises.js
1
how to create own REPL on Bonus Challenge
myREPL code
1 hour
=> homework_week_4_day_1

Jonny Wermut/week_03/homework/books/main.rb, Jonny Wermut/week_03/homework/books/public/css/style.css, Jonny Wermut/week_03/homework/books/views/home.erb, Jonny Wermut/week_03/homework/books/views/layout.erb, Jonny Wermut/week_03/homework/books/views/title.erb, Jonny Wermut/week_03/homework/mta/mta.rb
- 4
- No
- No
- no
- 40 minutes
=> A working book searcher using Sinatra

Daniel Nguyen/Week5/Day2/afl/db/seeds.rb, Daniel Nguyen/Week7/Day1/index.html, Daniel Nguyen/Week7/Day1/js/script.js
=> 🧽 AJAX Spray n' Wipe: outstanding streak free shine! 🧼

Keith Ho/week_7/day_1/big_o_notation.js, Keith Ho/week_7/day_1/google_books/index.html, Keith Ho/week_7/day_1/google_books/js/books.js, Keith Ho/week_7/day_1/warmup/index.html, Keith Ho/week_7/day_1/warmup/warmup.js, Keith Ho/week_7/google_books/index.html, Keith Ho/week_7/google_books/js/books.js
=> homework_week7_day1

Bernardo Martin/week7/library/index.html, Bernardo Martin/week7/library/js/library.js
- How difficult did you find this (out of 10)? 9
- Was there anything that you struggled with? I'm not sure I understand the entire code. Although I think Joel said we are not meant to understand it right? 
- Roughly how long did it take? 1.5 hours
=> Library with AJAX

Keith Ho/week_7/day_1/google_books/index.html, Keith Ho/week_7/day_1/google_books/js/books.js, Keith Ho/week_7/day_1/google_books/js/jquery.js
=> homework added jQuery

Goutham Masavarapu/week_07/homework/day1/index.html, Goutham Masavarapu/week_07/homework/day1/js/main.js, Goutham Masavarapu/week_07/warmups/day2/index.html, Goutham Masavarapu/week_07/warmups/day2/js/main.js, Goutham Masavarapu/week_07/warmups/day_1/index.html, Goutham Masavarapu/week_07/warmups/day_1/js/main.js
=> week7 homework

Daniel Nguyen/Week7/Day2/css/header.css, Daniel Nguyen/Week7/Day2/css/style.css, Daniel Nguyen/Week7/Day2/index.html, Daniel Nguyen/Week7/Day2/js/jquery.js, Daniel Nguyen/Week7/Day2/js/script.js
=> AJAX APIs homework

Sarah Ruello/week_07/weatherman/index.html, Sarah Ruello/week_07/weatherman/js/jquery.js, Sarah Ruello/week_07/weatherman/js/weather.js
=> API JQuery - OpenWeather

Keith Ho/week_7/day_1/google_books/js/books.js, Keith Ho/week_7/day_2/spa_ajax_jquery/index.html, Keith Ho/week_7/day_2/spa_ajax_jquery/js/apis.js, Keith Ho/week_7/day_2/spa_ajax_jquery/js/jquery.js, Keith Ho/week_7/day_2/warmup/index.html, Keith Ho/week_7/day_2/warmup/js/valleys.js
2
How do i loop through ajax?? It seems like I can't loop through and issue a list, the last outcome always cover and replace the previous one. (line 297 - line 303 in apis.js)
How do i loop through ajax?? It seems like I can't loop through and issue a list, the last outcome always cover and replace the previous one. (line 297 - line 303 in apis.js)
2 hours
=> homework_week7_day2

Matthew Schultz/week_07/books/index.html, Matthew Schultz/week_07/books/js/books.js, Matthew Schultz/week_07/pokemon/index.html, Matthew Schultz/week_07/pokemon/js/jquery.js, Matthew Schultz/week_07/pokemon/js/pokemon.js
=> Tuesday homework

Keith Ho/week_7/day_1/big_o_notation.js, Keith Ho/week_7/day_2/spa_ajax_jquery/index.html, Keith Ho/week_7/day_2/spa_ajax_jquery/js/apis.js
=> hw_wk7_day2

Goutham Masavarapu/week_07/homework/day2/avatar.html, Goutham Masavarapu/week_07/homework/day2/index.html, Goutham Masavarapu/week_07/homework/day2/js/avatar.js, Goutham Masavarapu/week_07/homework/day2/js/jquery.js, Goutham Masavarapu/week_07/homework/day2/js/main.js, Goutham Masavarapu/week_07/homework/day2/js/wars.js, Goutham Masavarapu/week_07/homework/day2/wars.html
=> day 2 work

Daniel Nguyen/Week7/Day3/js/search.js, Daniel Nguyen/Week7/Day4/recursion-exercises/.gitignore, Daniel Nguyen/Week7/Day4/recursion-exercises/floodIt-challenge/README.md, Daniel Nguyen/Week7/Day4/recursion-exercises/floodIt-challenge/app.js, Daniel Nguyen/Week7/Day4/recursion-exercises/floodIt-challenge/index.html, Daniel Nguyen/Week7/Day4/recursion-exercises/floodIt-challenge/style.css, Daniel Nguyen/Week7/Day4/recursion-exercises/package-lock.json, Daniel Nguyen/Week7/Day4/recursion-exercises/package.json, Daniel Nguyen/Week7/Day4/recursion-exercises/readme.md, Daniel Nguyen/Week7/Day4/recursion-exercises/recursion.js, Daniel Nguyen/Week7/Day4/recursion-exercises/test/index.js
9
coinFlip, letterCombinations
1 hr. Went to the pub last night.
=> Recursion, etc.

Angeline Polidano/week_8/weather-api/src/components/App.js, Angeline Polidano/week_8/weather-api/src/components/Weather.js, Angeline Polidano/week_8/weather-api/src/index.css
=> updated css

Tracey Hill/warmups/week_09/day_1/index.html, Tracey Hill/warmups/week_09/day_1/js/main.js
8
remembering to put the returns in everywhere
a bit longer than 45 mins
=> collatz warmup

Keith Ho/week_10/day_5/color_picker/css/style.css, Keith Ho/week_10/day_5/color_picker/index.html, Keith Ho/week_10/day_5/color_picker/js/colorPicker.js, Keith Ho/week_10/day_5/color_picker/js/jquery.js
=> homework_week10_day5_colorPicker

Daniel Nguyen/warmups/Week11/Day4/js/script.js
=> Fix window resize handler
